Upgrade TargetSdk, Kotlin, KSP, Gradle and Compose
mutualmobile/Barricade2 pull request #11
Opened 2023-02-16 16:49 UTC by pushpalroymm

- Bump TargetSdk to `33` 
- Bump Kotlin to `1.7.21`
- Bump  KSP to `1.7.21-1.0.8`
- Bump  Gradle to `7.5.1`
- Bump AGP to `7.4.0`
- Bump Compose Compiler to `1.4.0-alpha02`
- Add Compose BOM `2023.01.00`

2023-02-16 16:56 UTC, shubhamsinghmutualmobile commented on app/build.gradle
> +    id 'com.google.devtools.ksp' version "1.7.21-1.0.8"
Can we go to the latest stable version of both Kotlin and KSP? For Kotlin, it's `1.8.10` and for KSP, it's `1.8.10-1.0.9`

2023-02-16 16:58 UTC, shubhamsinghmutualmobile commented on build.gradle
> +    id 'com.android.library' version '7.4.0' apply false
Latest version is `7.4.1`

2023-02-16 16:58 UTC, shubhamsinghmutualmobile commented on build.gradle
> +    id 'org.jetbrains.kotlin.android' version '1.7.21' apply false
1.8.10

2023-02-16 16:59 UTC, shubhamsinghmutualmobile commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip
Latest stable version is 7.6

2023-02-16 16:59 UTC, shubhamsinghmutualmobile commented on settings.gradle
> +        id("com.google.devtools.ksp") version "1.7.21-1.0.8"
1.8.10-1.0.9

2023-02-16 16:59 UTC, shubhamsinghmutualmobile commented on settings.gradle
> +        id 'org.jetbrains.kotlin.android' version '1.7.21'
1.8.10

2023-02-16 17:00 UTC, shubhamsinghmutualmobile requested changes
Let's remove files coming in from `.idea`? And also, would it be a good time to introduce either `buildSrc` or composite builds to this project?

2023-02-16 18:44 UTC, pushpalroymm commented
> Let's remove files coming in from `.idea`? And also, would it be a good time to introduce either `buildSrc` or composite builds to this project?

Thanks for pointing it out @shubhamsinghmutualmobile.
I have removed the cached files and added them in .gitignore.

Sure we can work on buildSrc/composite build in a separate PR. 👍

2023-02-17 06:03 UTC, shubhamsinghmutualmobile approved these changes
LGTM

2023-02-17 07:41 UTC, ZeeshanShabbir approved these changes

2023-03-29 13:09 UTC, merged